name: client
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.10
  fluttertoast: ^8.2.2
  page_transition: ^2.0.9
  dio: ^5.3.2
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/layout/
    - assets/images/icons/
    - assets/images/characters/
    - assets/images/characters/portrait/
    - assets/images/classes/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/notosans/notosans_medium.otf
          weight: 200
        - asset: assets/fonts/notosans/notosans_medium.otf
          weight: 300
        - asset: assets/fonts/notosans/notosans_medium.otf
          weight: 400
        - asset: assets/fonts/notosans/notosans_medium.otf
          weight: 500
        - asset: assets/fonts/notosans/notosans_bold.otf
          weight: 600
        - asset: assets/fonts/notosans/notosans_bold.otf
          weight: 700
        - asset: assets/fonts/notosans/notosans_bold.otf
          weight: 800

    - family: KesselBold
      fonts:
        - asset: assets/fonts/kessel/kessel_205_w00_bold.ttf

    - family: GameStation
      fonts:
        - asset: assets/fonts/gamestation/gamestation_text.ttf

    - family: CabalFont
      fonts:
        - asset: assets/fonts/cabal/cabal_font.ttf
