name: client
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.10
  routemaster: ^1.0.1
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/notosans/notosans_medium.otf
          weight: 200
        - asset: assets/fonts/notosans/notosans_medium.otf
          weight: 300
        - asset: assets/fonts/notosans/notosans_medium.otf
          weight: 400
        - asset: assets/fonts/notosans/notosans_medium.otf
          weight: 500
        - asset: assets/fonts/notosans/notosans_bold.otf
          weight: 600
        - asset: assets/fonts/notosans/notosans_bold.otf
          weight: 700
        - asset: assets/fonts/notosans/notosans_bold.otf
          weight: 800
